name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - seaborn
  - networkx=2.1
  - graphviz
  - sympy
  - cvxopt
  - numba
  - spyder
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - rise
  - qgrid
